# github.com/jbenet/platform-vms/amd64/linux_ubuntu/base

Vagrant.configure("2") do |config|
  config.vm.box = 'precise64'
  config.vm.box_url = 'http://files.vagrantup.com/precise64.box'

  # synced files
  # config.vm.synced_folder ".", "/home/vagrant/synced"

end
