# github.com/jbenet/platform-vms/i386/linux_ubuntu/base

Vagrant.configure("2") do |config|
  config.vm.box = 'precise32'
  config.vm.box_url = 'http://files.vagrantup.com/precise32.box'

  # synced files
  # config.vm.synced_folder ".", "/home/vagrant/synced"

end
